{
 "title": "LangChain4j Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Input Token Cost",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gen_ai_client_token_usage_total{gen_ai_token_type=\"input\"}) * 0.00000015",
     "legendFormat": "Input Cost"
    }
   ]
  },
  {
   "title": "Output Token Cost",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gen_ai_client_token_usage_total{gen_ai_token_type=\"output\"}) * 0.00000015",
     "legendFormat": "Output Cost"
    }
   ]
  },
  {
   "title": "Total Consumption Cost",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gen_ai_client_token_usage_total{gen_ai_token_type=\"output\"} * 0.00000015) + sum(gen_ai_client_token_usage_total{gen_ai_token_type=\"input\"} * 0.00000015)",
     "legendFormat": "Total Cost"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "limit": 20,
     "query": "service.name = \"quarkus\"",
     "tableType": "traces"
    }
   ]
  },
  { "title": "JFokus Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "AI Service Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(langchain4j_aiservices_timed_seconds_sum[$__rate_interval])",
     "legendFormat": "{{aiservice}} - {{method}}"
    }
   ]
  },
  {
   "title": "Request Tokens Consumption",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(ai_service_method_name, gen_ai_request_model, gen_ai_token_type) (gen_ai_client_token_usage_total)",
     "legendFormat": "{{ai_service_method_name}}"
    }
   ]
  },
  {
   "title": "Response Tokens Consumption",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(ai_service_method_name, gen_ai_response_model, gen_ai_token_type) (gen_ai_client_token_usage_total)",
     "legendFormat": "{{ai_service_method_name}}"
    }
   ]
  },
  {
   "title": "Request Tokens Consumption",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(ai_service_method_name, gen_ai_request_model, gen_ai_token_type) (gen_ai_client_token_usage_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Tokens Consumption",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(ai_service_method_name, gen_ai_response_model, gen_ai_token_type) (gen_ai_client_token_usage_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}